services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - dsa-network

networks:
  dsa-network:
    driver: bridge

volumes:
  db_data: